name: implicitly_animated_list
version: 2.2.0
description: A Flutter widget that implicitly animates a list whenever it rebuilds with new items.
repository: https://github.com/marcelgarus/implicitly_animated_list

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  list_diff: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
